package com.lss.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Id
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Name
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Id
     *
     * @return the value of user.Id
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Id
     *
     * @param id the value for user.Id
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Name
     *
     * @return the value of user.Name
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Name
     *
     * @param name the value for user.Name
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
     * @mbggenerated Mon Aug 07 18:15:13 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}